---
title: "p8105_hw4_xy2364_yt2604 problem 2"
author: "Yuqi Tu and Xin Yin"
date: "October 24, 2017"
output: html_document
---

```{r library}
library(tidyverse)
library(haven)
library(janitor)
library(ggridges)
library(ggthemes)
library(lubridate)
library(haven)
library(stats)
library(readr)
```

```{r read data}
pols_month_data = 
  read_csv("pols-month.csv") %>% 
  clean_names() %>% 
  mutate(mon = as.Date(mon,format = "%Y-%m-%d")) %>% 
  mutate(month = lubridate::floor_date((mon), unit = "month"))


GDP_data = read_csv("GDP.csv") %>% 
  clean_names() %>% 
  mutate(date = as.Date(date,format = "%Y-%m-%d")) %>% 
  mutate(month = lubridate::floor_date((date), unit = "month"))

combined_data = left_join(pols_month_data,GDP_data, by = "month")
```


```{r plot data}
plot_data = 
  combined_data %>%
  select(prez_dem, month, value) %>%
  mutate(value = as.numeric(value)) %>% 
  drop_na() %>% 
  mutate(prez_dem = recode(prez_dem,"0" = "republican", "1" ="democratic" ))


plot2 = ggplot(plot_data,aes(x = month, y = value, color = prez_dem)) + 
  geom_bar(stat = "identity", fill= "white") + 
    ggtitle("GDP Performance By Party of Presidents During 1947-2015") +
    ylab("GDP value")
plot2
  
plot = ggplot(plot_data, aes(x = month, y = value, color = prez_dem))+
  geom_line()
plot  
```

* Comments: Before 1980, the GDP value controlled under two parties was fluctuating throughout their own rulling period. After 1980, the GDP value became more stable within each party's rulling period. But it appears that after 1980, the GDP value on average  governed by republican party was higher than that governed by democratic party.


